// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addWriterTitlewriter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addWriterTitlewriter));
        
        string IMigrationMetadata.Id
        {
            get { return "202211031231105_add-WriterTitle-writer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
